### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by whitingx**
Added SmashingMag FE performance checklist.

### CODE REVIEW

**Comment by huyingjie** [comment]
@whitingx Thank you. The list seems too long. Can someone reduce the size?

**Comment by whitingx** [comment]
@huyingjie in regard to

> The list seems too long. Can someone reduce the size?

can you clarify what you mean here? The list itself, the link to the list, something else? Thanks ツ

**Comment by huyingjie** [comment]
I hope the checklist is like https://frontendchecklist.io/ , http://webdevchecklist.com/, and https://github.com/virajkulkarni14/WebDeveloperSecurityChecklist
Your explanation for each bullet point is too long.

**Comment by whitingx** [comment]
Thanks for clarifying @huyingjie ツ - I've no control over the checklist/article content here so can't reduce anything down.

**Pull request closed without merging**
